apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}-configure-common
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
data:

  template-common.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">
        <address-settings>
          <!-- if you define auto-create on certain queues, management has to be auto-create -->
          <address-setting match="activemq.management#">
            <dead-letter-address>DLQ</dead-letter-address>
            <expiry-address>ExpiryQueue</expiry-address>
            <redelivery-delay>5000</redelivery-delay>
            <max-delivery-attempts>3</max-delivery-attempts>
            <redelivery-collision-avoidance-factor>0.15</redelivery-collision-avoidance-factor>
            <max-redelivery-delay>50000</max-redelivery-delay>
            <!-- with -1 only the global-max-size is in use for limiting -->
            <max-size-bytes>-1</max-size-bytes>
            <message-counter-history-day-limit>10</message-counter-history-day-limit>
            <address-full-policy>PAGE</address-full-policy>
            <auto-create-queues>true</auto-create-queues>
            <auto-create-addresses>true</auto-create-addresses>
            <auto-create-jms-queues>true</auto-create-jms-queues>
            <auto-create-jms-topics>true</auto-create-jms-topics>
            <auto-delete-queues>true</auto-delete-queues>
            <auto-delete-addresses>true</auto-delete-addresses>
            <enable-metrics>true</enable-metrics>
          </address-setting>
          <!--default for catch all-->
          <address-setting match="#">
            <dead-letter-address>DLQ</dead-letter-address>
            <expiry-address>ExpiryQueue</expiry-address>
            <min-expiry-delay>10</min-expiry-delay>
            <max-expiry-delay>100</max-expiry-delay>
            <redelivery-delay>5000</redelivery-delay>
            <max-delivery-attempts>3</max-delivery-attempts>
            <redelivery-collision-avoidance-factor>0.15</redelivery-collision-avoidance-factor>
            <max-redelivery-delay>50000</max-redelivery-delay>
            <!-- with -1 only the global-max-size is in use for limiting -->
            <max-size-bytes>-1</max-size-bytes>
            <message-counter-history-day-limit>10</message-counter-history-day-limit>
            <auto-delete-addresses-delay>5000</auto-delete-addresses-delay>
            <address-full-policy>PAGE</address-full-policy>
            <auto-create-queues>true</auto-create-queues>
            <auto-create-addresses>true</auto-create-addresses>
            <auto-create-jms-queues>true</auto-create-jms-queues>
            <auto-delete-jms-queues>true</auto-delete-jms-queues>
            <auto-create-jms-topics>true</auto-create-jms-topics>
            <auto-delete-jms-topics>true</auto-delete-jms-topics>
            <auto-delete-queues>true</auto-delete-queues>
            <auto-delete-addresses>true</auto-delete-addresses>
            <auto-delete-created-queues>true</auto-delete-created-queues>
            <enable-metrics>true</enable-metrics>
          </address-setting>
        </address-settings>
        <broker-plugins>
          <broker-plugin class-name="org.apache.activemq.artemis.core.server.plugin.impl.LoggingActiveMQServerPlugin">
            <property key="LOG_ALL_EVENTS" value="true"/>
            <property key="LOG_CONNECTION_EVENTS" value="true"/>
            <property key="LOG_SESSION_EVENTS" value="true"/>
            <property key="LOG_CONSUMER_EVENTS" value="true"/>
            <property key="LOG_DELIVERING_EVENTS" value="true"/>
            <property key="LOG_SENDING_EVENTS" value="true"/>
            <property key="LOG_INTERNAL_EVENTS" value="true"/>
          </broker-plugin>
        </broker-plugins>
      </core>
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core">

        <cluster-user>{{ .Values.artemisUser }}</cluster-user>
        <cluster-password>{{ .Values.artemisPassword }}</cluster-password>
        <connection-ttl-override>60000</connection-ttl-override>

        {{- $name := default .Chart.Name .Values.nameOverride -}}
        {{- $fullname := include "artemis.fullname" . -}}
        {{- $releaseName := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
        {{- $releaseNamespace := .Release.Namespace -}}

        <connectors>
          {{ range $i,$t := until (int .Values.replicas) }}
          {{ range tuple "master" "slave" }}
          <connector name="{{ $fullname }}-{{ . }}-{{ $i }}">tcp://{{ $fullname }}-{{ . }}-{{ $i }}.{{ $releaseName }}-{{ . }}.{{ $releaseNamespace }}.svc.cluster.local:61616</connector>
          {{ end }}
          {{end}}
        </connectors>
        <cluster-connections>
          <cluster-connection name="{{ $releaseName }}">
            <connector-ref>netty-connector</connector-ref>
            <retry-interval>500</retry-interval>
            <retry-interval-multiplier>1.1</retry-interval-multiplier>
            <max-retry-interval>5000</max-retry-interval>
            <initial-connect-attempts>-1</initial-connect-attempts>
            <reconnect-attempts>-1</reconnect-attempts>

            <message-load-balancing>ON_DEMAND</message-load-balancing>
            <max-hops>1</max-hops>

            <static-connectors>
            {{ range $i,$t := until (int .Values.replicas) }}
              {{ range tuple "master" "slave" }}
              <connector-ref>{{ $fullname }}-{{ . }}-{{ $i }}</connector-ref>
              {{ end }}
            {{ end }}
            </static-connectors>
          </cluster-connection>
        </cluster-connections>
      </core>
    </configuration>

